apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dsodemo
  name: dsodemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dsodemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dsodemo
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'dso-demo'
        vault.hashicorp.com/agent-inject-secret-database: 'secret/dso-demo/database'
    spec:
      serviceAccountName: dso-demo
      containers:
      - image: kushwap1/dsodemo
        name: dsodemo
        ports:
        - containerPort: 8080
        resources: {}
status: {}
